### ISSUE TITLE
"Downloading a list of Game Title IDs..." throws error

### ISSUE THREAD

**Issue by gnaomo** [rlaphoenix/nton#18]
I believe it's because tinfoil.io is restricted in my county

```
PS C:\Users\gnaomo\Downloads\nsp> nton
Downloading a list of Game Title IDs...
Traceback (most recent call last):
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000200C5C45690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tinfoil.media', port=443): Max retries exceeded with url: /Title/ApiJson/?rating_content=&language=&category=&region=ar%2Cat%2Cau%2Cbe%2Cbg%2Cbr%2Cca%2Cch%2Ccl%2Ccn%2Cco%2Ccy%2Ccz%2Cde%2Cdk%2Cee%2Ces%2Cfi%2Cfr%2Cgb%2Cgr%2Chk%2Chr%2Chu%2Cie%2Cit%2Cjp%2Ckr%2Clt%2Clu%2Clv%2Cmt%2Cmx%2Cnl%2Cno%2Cnz%2Cpe%2Cpl%2Cpt%2Cro%2Cru%2Cse%2Csi%2Csk%2Cus%2Cxx%2Cza%2Czh&rating=&_=1691236023573 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C5C45690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Scripts\nton.exe\__main__.py", line 4, in <module>
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\nton\main.py", line 17, in <module>
    from nton import __version__, nstool, title_ids
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\nton\title_ids.py", line 482, in <module>
    game_title_ids = get_game_title_ids()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\nton\title_ids.py", line 437, in get_game_title_ids
    res = requests.get(
          ^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gnaomo\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tinfoil.media', port=443): Max retries exceeded with url: /Title/ApiJson/?rating_content=&language=&category=&region=ar%2Cat%2Cau%2Cbe%2Cbg%2Cbr%2Cca%2Cch%2Ccl%2Ccn%2Cco%2Ccy%2Ccz%2Cde%2Cdk%2Cee%2Ces%2Cfi%2Cfr%2Cgb%2Cgr%2Chk%2Chr%2Chu%2Cie%2Cit%2Cjp%2Ckr%2Clt%2Clu%2Clv%2Cmt%2Cmx%2Cnl%2Cno%2Cnz%2Cpe%2Cpl%2Cpt%2Cro%2Cru%2Cse%2Csi%2Csk%2Cus%2Cxx%2Cza%2Czh&rating=&_=1691236023573 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C5C45690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

**Comment by rlaphoenix** [comment]
Hi, I haven't considered that a problem when it doesn't load without cache or when the cache gets old. So I've decided to just delete that behavior entirely and go for a local cache that comes bundled with the project. You can still manually update the cache by running `nton update-game-ids`. See https://github.com/rlaphoenix/nton/commit/1d8b363b65e99f5bfa628989d3cc6b09499621a5
