### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by PorpoisefullyOffensive** [rlaphoenix/nton#9]
I may just be doing something wrong but I run nton D:/hbmenu.nro and get: 

```
PS C:\Users\Chris\Documents\Switch\Apps and Homebrew> nton build "D:\hbmenu.nro"
2023-01-28 03:17:54 [I] nton.main : nton version 1.2.0 Copyright (c) 2022-2023 rlaphoenix
2023-01-28 03:17:54 [I] nton.main : https://github.com/rlaphoenix/nton
2023-01-28 03:17:54 [I] build : Building!
2023-01-28 03:17:54 [I] build : NRO checked and verified
2023-01-28 03:17:54 [I] build : Title ID: 010d6fd3b35cd000
2023-01-28 03:17:54 [I] build : Enabled Video Capture
2023-01-28 03:17:54 [I] build : Removed User Account Save Data Allocation
2023-01-28 03:17:54 [I] build : Removed User Account Save Data Journal Allocation
2023-01-28 03:17:54 [I] build : Title Name: nx-hbmenu
2023-01-28 03:17:54 [I] build : Publisher: switchbrew
2023-01-28 03:17:54 [I] build : Version: 3.5.1
Traceback (most recent call last):
  File "c:\users\chris\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\Scripts\nton.exe\__main__.py", line 7, in <module>
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\site-packages\nton\main.py", line 283, in build
    "-strip", str(icon_file.absolute())
  File "c:\users\chris\appdata\local\programs\python\python37\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "c:\users\chris\appdata\local\programs\python\python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\chris\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "c:\users\chris\appdata\local\programs\python\python37\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
PS C:\Users\Chris\Documents\Switch\Apps and Homebrew>
```

**Comment by PorpoisefullyOffensive** [comment]
This was an issue with my install, I removed everything and tried again, now works as intended.
